module.exports = {
    // this secret is used to authenticate the JWT generated by the website to check its authenticity 
    // 'to make sure its generated by our site'.
    'secret': 'dahsecret3shanlsecuritybeta3etlwebsite:D',
    // the url of the mongoDB
    'database': 'mongodb://localhost/realytics_users_db'
};